print("Bienvenidos a la calculadora de huella de carbono de GreenData! \nIngrese su nombre para continuar:")
nombre = input()
puntaje = 0
print("Hola ", nombre, " este test cuenta de 3 etapas: unas preguntas sobre tu vivienda, algunas sobre tu transporte y alunas sobre tus hábitos de consumo.\nAl finalizar, te dirá a que tipo de categoría corresponde tu huella de carbono.\nComencemos!")
print("¿De qué tamaño es tu vivienda? \n1)Menor a 60 mts2 \n2)Entre 60mts2 y 120 mts2 \n3)Mayor de 120 mts2")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Qué tipo de vivienda es? \n1)Habitación \n2)Departamento \n3)Casa")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Cuántas personas habitan en tu vivienda? \n1)Mas de 5 \n2)Entre 2 y 5 \n3)1")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Qué tipo de calefación usas? \n1)Leña \n2)Electricidad \n3)Gas")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Cuántos electrodomésticos posees en tu vivienda? \n1)5 o menos \n2)Entre 5 y 10 \n3)Más de 10")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Tenés aire acondicionado? \n1)No \n2)Si")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿De qué tipo de planta electrica proviene tu energia? \n1)Renovable \n2)No lo sé \n3)No renovable")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Cuántas mascotas tenés? \n1)Ninguna \n2)1\n3)Entre 2 y 5 \n4)Mas de 5")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Tenés vehículos motorizados?¿Cuántos? \n1)Ninguno \n2)1  \n3)2 o más")
respuesta = input()
if int(respuesta) in [2,3]:
    puntaje = puntaje + int(respuesta)
    print("¿Cuántos años tiene tu vehículo? \n1)Menos de 5 \n2)Entre 5 y 15 \n3)Más de 15")
    respuesta = input()
    puntaje = puntaje + int(respuesta)
    print("¿De qué tamaño es? \n1)Chico \n2)Mediano \n3)Grande")
    respuesta = input()
    puntaje = puntaje + int(respuesta)
    print("¿Qué tipo de combustible usa? \n1)Electrico \n2)Gasoil \n3)Nafta")
    respuesta = input()
    puntaje = puntaje + int(respuesta)
    print("¿Cuantos KM por semana recorres en tu vehículo? \n1)Menos de 1.000KM \n2)Entre 1.000KM y 2.000 KM \n3)Más de 2.000 KM")
    respuesta = input()
    puntaje = puntaje + int(respuesta)
    print("¿Compartís vehículo? \n1)Si \n2)No")
    respuesta = input()
    puntaje = puntaje + int(respuesta)
    print("¿Qué medio de transporte usas con mayor frecuencia? \n1)Pie o bicicleta \n2)Transporte público \n3)Taxi o auto propio")
    respuesta = input()
    puntaje = puntaje + int(respuesta)
else:
    print("¿Qué medio de transporte usas con mayor frecuencia? \n1)Pie o bicicleta \n2)Transporte público \n3)Taxi o auto propio")
    respuesta = input()
    puntaje = puntaje + int(respuesta)
print("¿Con qué frecuencia comes carne? \n1)Nunca \n2)2 a 3 veces por semana \n3)Más de 3 veces por semana")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Con qué frecuencia comes comidas totalmente vegetarianas? \n1)Más de 3 veces por semana \n2)2 a 3 veces por semana \n3)Nunca")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Cuál es tu actitud respecto al desperdicio de comida? \n1)Hago lo posible para evitar el desperdicio de comida \n2)No pienso en ello")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Cuál es tu actitud respecto al consumo de plastico de un solo uso? \n1)Hago lo posible para evitar el plastico de un solo uso \n2)No pienso en ello")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Reciclás? \n1)Si \n2)No")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Con qué frecuencia compras cosas nuevas? \n1)Solo cuando es necesario \n2)Algunas veces \n3)Me encanta comprar cosas nuevas")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Con qué frecuencia compras cosas de segunda mano? \n1)Cuando compro algo, muchas veces es de segunda mano \n2)Algunas veces \n3)Nunca")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Regalás o vendés tus articulos de segunda mano? \n1)Si \n2)Algunas veces \n3)Por lo general tiro las cosas que no uso")
respuesta = input()
puntaje = puntaje + int(respuesta)
print("¿Alguna vez compensaste tu huella de carbono? \n1)Si \n2)No")
respuesta = input()
puntaje = puntaje + int(respuesta)
if puntaje < 30:
    print("Felicitaciones! Sos un amigo del clima y tu emision de CO2 no supera las 3 Tm! A seguir así!")
elif puntaje >=30 and puntaje<=60: print("Tu emision de CO2 está en el promedio global (4Tm/año). Te recomendamos cambiar algunos hábitos para contribuir con el medio ambiente!")
else:
    print("Sos un villano del clima! Tus emisiones de CO2 superan el promedio y necesitamos tu colaboración para contribuir con el medio ambiente!!")
print(" ")
print("¿Sabías que una hectárea de bosque de 20 años de edad es capaz de captar la misma cantidad de CO2 que una persona genera cada año?\nSumate al desafío de plantar un arbol para ayudar al planeta!")
